version: 1.0.{build}
configuration: Release
before_build:
  - cmd: nuget restore
build:
  verbosity: detailed
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
nuget:
  account_feed: true
  project_feed: true
deploy:
  provider: NuGet
  api_key:
    secure: Ryx7Ku2/g/gwshXCljkLAKbCYBZeReHKv6g78eGoo5FBxhVynENg/Aqy7OcdGv0e
  skip_symbols: false
  artifact: /.*\.nupkg/
test: off