version: 1.0.{build}
configuration: Release
before_build:
  - cmd: nuget restore
build:
  verbosity: detailed
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
nuget:
  account_feed: true
  project_feed: true
deploy:
  provider: NuGet
  api_key:
    secure: F7Ah4ChBiRhqgLoK9OCpVrpacZtiLgQ5RKDmMfaLMJYiK/V0lwIV7YST13RjfZoj
  skip_symbols: false
  artifact: /.*\.nupkg/
test: off